CREATE DATABASE QLFAD
GO
USE QLFAD
GO
CREATE TABLE NHANVIEN
(
	MaNV char(20),
	Ho_Ten NVARCHAR(40) NOT NULL,
	GioiTinh NCHAR(3) NOT NULL,
	NgaySinh DATE NOT NULL,
	SDT CHAR(12) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL
	CONSTRAINT PK_MaNV PRIMARY KEY(MaNV)
)
GO
CREATE TABLE TAIKHOAN
(
TENTK VARCHAR(50),
MATKHAU VARCHAR(20) NOT NULL,
QUYEN VARCHAR(20) NOT NULL CHECK (QUYEN='NHANVIEN' OR QUYEN='ADMIN'),
MaNV char(20) NOT NULL,
CONSTRAINT PK_TENTK PRIMARY KEY(TENTK),
CONSTRAINT FK_IDNVTK FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
)
GO
CREATE TABLE HINHNV
(
IDHINH INT IDENTITY(1,1),
HINH IMAGE,
MaNV char(20),
CONSTRAINT PK_IDHINHNV PRIMARY KEY(IDHINH),
CONSTRAINT FK_MaNVHINH FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV),

)
GO
CREATE TABLE BAN
(
IDBAN INT IDENTITY(1,1),
TEN NVARCHAR(50) NOT NULL,
TRANGTHAI NVARCHAR(20) CHECK(TRANGTHAI=N'Trống' or TRANGTHAI=N'Có Người') default N'Trống' not null,
ODER INT NOT NULL,
CONSTRAINT PK_IDBAN PRIMARY KEY(IDBAN)
)
GO
CREATE TABLE DANHMUC_SANPHAM
(
IDDM INT IDENTITY(1,1),
TENDM NVARCHAR(50) NOT NULL,
CONSTRAINT PK_IDDM PRIMARY KEY(IDDM)
)
GO
CREATE TABLE SANPHAM
(
IDSANPHAM INT IDENTITY(1,1),
IDDM INT NOT NULL,
TENSANPHAM NVARCHAR(100) NOT NULL,
DONGIA FLOAT DEFAULT 0 NOT NULL,
CONSTRAINT PK_IDSANPHAM PRIMARY KEY(IDSANPHAM),
CONSTRAINT FK_IDDM FOREIGN KEY(IDDM) REFERENCES DANHMUC_SANPHAM(IDDM)
)
GO
CREATE TABLE HOADON
(
IDHOADON INT IDENTITY(1,1),
IDBAN INT NOT NULL,
MaNV char(20) NOT NULL,
NGAYLAP DATE NOT NULL DEFAULT GETDATE(),
TRANGTHAI NVARCHAR(20) DEFAULT N'Chưa' NOT NULL,
CONSTRAINT PK_IDHOADON PRIMARY KEY(IDHOADON),
CONSTRAINT FK_IDBANHD FOREIGN KEY(IDBAN) REFERENCES BAN(IDBAN),
CONSTRAINT FK_MaNVHD FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
)
GO
CREATE TABLE CTHD
(
IDCTHD INT IDENTITY(1,1),
IDHOADON INT NOT NULL,
IDSANPHAM INT NOT NULL,
SOLUONG INT DEFAULT 0 NOT NULL,
CONSTRAINT PK_IDCTHD PRIMARY KEY(IDCTHD),
CONSTRAINT FK_IDHOADONCTHD FOREIGN KEY(IDHOADON) REFERENCES HOADON(IDHOADON),
CONSTRAINT FK_IDSANPHAMCTHD FOREIGN KEY(IDSANPHAM) REFERENCES SANPHAM(IDSANPHAM)
)
GO
CREATE TABLE HOADON_OLD
(
IDHD_OLD INT IDENTITY(1,1),
IDHOADON INT NOT NULL ,
IDBAN INT NOT NULL,
MaNV char(20) NOT NULL,
NGAYLAP DATE NOT NULL DEFAULT GETDATE(),
TRANGTHAI NVARCHAR(20) DEFAULT N'Chưa' NOT NULL,
TONGTIEN FLOAT DEFAULT 0 NOT NULL
CONSTRAINT PK_IDHD_OLD PRIMARY KEY(IDHD_OLD),
CONSTRAINT IDHD_DUYNHAT UNIQUE (IDHOADON),
)
GO
CREATE TABLE CTHD_OLD
(
	IDCTHD_OLD INT IDENTITY(1,1),
	IDHOADON_OLD INT NOT NULL,
	IDSANPHAM INT NOT NULL,
	SOLUONG INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_IDCTHD1 PRIMARY KEY(IDCTHD_OLD),
	CONSTRAINT FK_IDHOADONCTHD_OLD FOREIGN KEY(IDHOADON_OLD) REFERENCES HOADON_OLD(IDHOADON),
)
GO
